inputs:
['multiplexing_VH_decoder.py', '1', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '0']
make HGP code
start simulation
2024-03-16 13:29:54.079869
simulation finished
2024-03-16 19:20:16.274669
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=1_rate=0.0-1.0_deterministic_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '8', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '2']
make HGP code
start simulation
2024-03-16 13:29:54.431664
simulation finished
2024-03-16 19:23:47.094234
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=8_rate=0.0-1.0_row_col_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '2', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '1']
make HGP code
start simulation
2024-03-16 13:29:54.308880
simulation finished
2024-03-16 19:36:34.265669
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=2_rate=0.0-1.0_random_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '16', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '1']
make HGP code
start simulation
2024-03-16 13:29:55.206610
simulation finished
2024-03-16 19:39:41.239749
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=16_rate=0.0-1.0_random_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '16', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '0']
make HGP code
start simulation
2024-03-16 13:29:55.198276
simulation finished
2024-03-16 19:46:42.432592
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=16_rate=0.0-1.0_deterministic_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '4', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '1']
make HGP code
start simulation
2024-03-16 13:29:54.178998
simulation finished
2024-03-16 19:54:03.984918
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=4_rate=0.0-1.0_random_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '4', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '0']
make HGP code
start simulation
2024-03-16 13:29:54.318662
simulation finished
2024-03-16 20:07:02.407534
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=4_rate=0.0-1.0_deterministic_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '2', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '2']
make HGP code
start simulation
2024-03-16 13:29:54.529120
simulation finished
2024-03-16 20:09:47.974230
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=2_rate=0.0-1.0_row_col_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '16', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '2']
make HGP code
start simulation
2024-03-16 13:29:55.076956
simulation finished
2024-03-16 20:10:19.311626
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=16_rate=0.0-1.0_row_col_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '4', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '2']
make HGP code
start simulation
2024-03-16 13:29:54.504400
simulation finished
2024-03-16 20:10:46.731530
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=4_rate=0.0-1.0_row_col_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '8', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '1']
make HGP code
start simulation
2024-03-16 13:29:56.218604
simulation finished
2024-03-16 20:17:00.135996
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=8_rate=0.0-1.0_random_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '8', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '0']
make HGP code
start simulation
2024-03-16 13:29:54.506481
simulation finished
2024-03-16 20:17:01.558579
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=8_rate=0.0-1.0_deterministic_assignment.json'
inputs:
['multiplexing_VH_decoder.py', '2', '1', '0', '10000', '1.00', '0.00', '100', '16', '2', '4', '0']
make HGP code
start simulation
2024-03-16 13:29:54.334735
simulation finished
2024-03-16 20:37:48.832012
Traceback (most recent call last):
  File "multiplexing_VH_decoder.py", line 646, in <module>
    main_with_LE()
  File "multiplexing_VH_decoder.py", line 640, in main_with_LE
    dt_finished=dt_finished
  File "multiplexing_VH_decoder.py", line 495, in save_results_with_DFLE
    with open(file_name, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/results_HGP_n320_m=2_rate=0.0-1.0_deterministic_assignment.json'
